In [827]:
##importing required library

import numpy as np

In [828]:
np.set_printoptions(linewidth=100, precision =2, suppress=1 )

In [829]:
##importing the data
##skipping the header columns for now

raw_data= np.genfromtxt("loan-data_1.csv", delimiter=";",
                         autostrip=1, skip_header=1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [830]:
raw_data.shape

(10000, 14)

In [831]:
## Getting the mean of all the columns in raw_data

raw_mean= np.nanmean(raw_data, axis=0)
raw_mean

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/664877263.py:3: RuntimeWarning: Mean of empty slice
  raw_mean= np.nanmean(raw_data, axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [832]:
raw_max=np.nanmax(raw_data, axis=0)
raw_min=np.nanmin(raw_data, axis=0)

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/4051618153.py:1: RuntimeWarning: All-NaN slice encountered
  raw_max=np.nanmax(raw_data, axis=0)
C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/4051618153.py:2: RuntimeWarning: All-NaN slice encountered
  raw_min=np.nanmin(raw_data, axis=0)


In [833]:
##creating an array of maximum, mean and minimum values of all the 14 columns

raw_stats= np.array([raw_max, raw_mean, raw_min])
raw_stats

array([[68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ]])

In [834]:
temporary_fill = np.nanmax(raw_data) + 1
temporary_fill

68616520.0

# Seperating the columns with string and numeric values

In [835]:
##getting the indices of columns with string values 


col_strings= np.argwhere(np.isnan(raw_mean)).squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [836]:
##getting the indices of columns with string values 

col_numeric= np.argwhere(np.isnan(raw_mean)==False).squeeze()
col_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Reimporting the data

In [837]:
## array with string values 

data_string= np.genfromtxt("loan-data_1.csv", delimiter=";",
                            usecols= col_strings, skip_header=1,
                            dtype=np.str, autostrip=1)
data_string

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/1281211472.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str, autostrip=1)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [838]:
## array with numeric values

data_numeric= np.genfromtxt("loan-data_1.csv", delimiter=";",
                            usecols= col_numeric, skip_header=1,
                            autostrip=1, filling_values= temporary_fill )
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [839]:
np.isnan(data_numeric).sum()

0

# Importing the headings 

In [840]:
header_full = np.genfromtxt("loan-data_1.csv", delimiter=";"
                            , skip_footer=raw_data.shape[0],
                            autostrip=1,dtype=np.str )
header_full

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/2939851677.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  autostrip=1,dtype=np.str )


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [841]:
## Seperating the headers of string columns from that of numeric columns

header_strings= header_full[col_strings]
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [842]:
header_numeric= header_full[col_numeric]
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Manipulating String Data

## Issue date

In [843]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [844]:
header_strings[0]='issue_date'

In [845]:
np.unique(data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [846]:
## As all the data is from 2015, we can strip the '-15' part from the issue date column

data_string[:,0]= np.chararray.strip(data_string[:,0],'-15')
np.unique(data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [847]:
## As the issue date is not mentioned by some clients, we will mark them as 'red_flag' for further analysis


data_string[:,0]= np.where(data_string[:,0]=='',
                           'red_flag',
                            data_string[:,0])
np.unique(data_string[:,0])

array(['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep',
       'red_flag'], dtype='<U69')

## Loan Status

In [848]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [849]:
np.unique(data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [850]:
## Loan status is not mentioned by some clients, so let's mark their status filed, 'red_flag'
## Also, default, charged-off and payment late by 31 to 120 days will be marked 'red_flag'


bad_status= np.array(['Late (31-120 days)','Default','Charged Off', '' ])

In [851]:
## Marking all the other fields of status column as 'OK'


data_string[:,1]= np.where(np.isin(data_string[:,1],bad_status),
                           'red_flag',
                            'OK')
np.unique(data_string[:,1])

array(['OK', 'red_flag'], dtype='<U69')

## Term Loan

In [852]:
np.unique(data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [853]:
## As mentions earlier, it is better to consider the worst when a field is not mentioned by the client
## so changing the null values in term loan section to 60-months
## Also we will remove the ' months' part from the string for convinient analysis


data_string[:,2]= np.chararray.strip(data_string[:,2],' months')
np.unique(data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [854]:
data_string[:,2]=np.where(data_string[:,2]=='',
                          '60',
                           data_string[:,2])
np.unique(data_string[:,2])

array(['36', '60'], dtype='<U69')

In [855]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Loan-Grade and Sub-Grade

In [856]:
## As loan-grade and sub-grade are linked, we can try to manipulate them together

In [857]:
np.unique(data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [858]:
np.unique(data_string[:,4], return_counts=1)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [859]:
## For every element we saw in grade, we have five different elements in sub grade.
## Therefore, if the data is complete, any information we can get from the great column can also be obtained
## from the sub grade column that in theory makes the former redundant.



In [860]:
## As there are a few null values in the subgrade column, we can check if the same client has mentioned
## an apropriate value in the grade column and handle the missing values accordingly


for i in np.unique(data_string[:,3])[1:]:
    data_string[:,4]= np.where((data_string[:,4]=='') & (data_string[:,3]==i),
                                i + '5',
                                data_string[:,4])
np.unique(data_string[:,4], return_counts=1)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [861]:
## For the id's(clients) haveing null values in both grade and sub-grade column, we can mark those 
## values as 'red_flag'


data_string[:,4]= np.where(data_string[:,4]=='',
                           'red_flag',
                            data_string[:,4])
np.unique(data_string[:,4], return_counts=1)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'red_flag'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

In [862]:
np.unique(data_string[:,4]).shape

(36,)

## Converting sub-grade to numbers

In [863]:
## Let's construct a dictionary called dict_grade
## In this dictionary, every key will be a unique sub-grade represented as a string, while the value associated
## with it will designate a rank of trustworthiness and it will be a number


key= list(np.unique(data_string[:,4]))
values= list(range(1, np.unique(data_string[:,4]).shape[0] +1))
dict_grade= dict(zip(key,values))
dict_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'red_flag': 36}

In [864]:
for i in key:
    data_string[:,4]= np.where(data_string[:,4]==i,
                               dict_grade[i],
                               data_string[:,4])
np.unique(data_string[:,4], return_counts=1)

(array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
        '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
        '4', '5', '6', '7', '8', '9'], dtype='<U69'),
 array([285, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 278, 288, 235, 162, 171, 139, 160,
         94,  52,  34,  43, 239,  24,  19,  10,   3,   7,   5,   9, 323, 592, 509, 517, 530, 553],
       dtype=int64))

In [865]:
data_string[:,4]=np.where(data_string[:,4]=='36',
                          'red_flag',
                          data_string[:,4])
np.unique(data_string[:,4], return_counts=1)

(array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
        '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '4', '5',
        '6', '7', '8', '9', 'red_flag'], dtype='<U69'),
 array([285, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 278, 288, 235, 162, 171, 139, 160,
         94,  52,  34,  43, 239,  24,  19,  10,   3,   7,   5, 323, 592, 509, 517, 530, 553,   9],
       dtype=int64))

## Removing grade column

In [866]:
data_string[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [867]:
data_string=np.delete(data_string, 3, axis=1)

In [868]:
data_string[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [869]:
header_strings=np.delete(header_strings, 3)
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Verification Status

In [870]:
np.unique(data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [871]:
## Marking the not mentioned values and the not verified field as 'red_flag'
## Also we can mark the verified field as 'OK' for convinience in further analysis



data_string[:,4]= np.where((data_string[:,4]=='') | (data_string[:,4]=='Not Verified'),
                            'red_flag',
                            'OK')
np.unique(data_string[:,4])

array(['OK', 'red_flag'], dtype='<U69')

## URL

In [872]:
data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [873]:
## Let's remove the repeting part in all the URLs using the strip function


data_string[:,5]=np.chararray.strip(data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [874]:
## The remaining part of the URL seems to be a unique value for every row
## Let us verify if the remaining part of URL matches with the IDs in the numeric data.


np.array_equal(data_numeric[:,0].astype(dtype=np.int32),
               data_string[:,5].astype(dtype=np.int32))

True

In [875]:
data_string=np.delete(data_string, 5, axis=1)
header_strings= np.delete(header_strings, 5)

In [876]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [877]:
data_string

array([['May', 'OK', '36', '13', 'OK', 'CA'],
       ['red_flag', 'OK', '36', '5', 'OK', 'NY'],
       ['Sep', 'OK', '36', '10', 'OK', 'PA'],
       ...,
       ['Jun', 'OK', '36', '5', 'OK', 'CA'],
       ['Apr', 'OK', '36', '17', 'OK', 'OH'],
       ['Dec', 'OK', '36', '4', 'red_flag', 'IL']], dtype='<U69')

In [878]:
data_string.shape

(10000, 6)

In [879]:
header_strings.shape

(6,)

## State Address

In [880]:
np.unique(data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [881]:
## Let's mark the values not mentioned by the client as 'red_flag'


data_string[:,5]=np.where(data_string[:,5]=='',
                          'red_flag',
                           data_string[:,5])
np.unique(data_string[:,5])

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS',
       'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ',
       'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT',
       'WA', 'WI', 'WV', 'WY', 'red_flag'], dtype='<U69')

In [882]:
## As we can see, the states are in abbrivation form
## For convience in analysis, lets change it to the full-form name of the states

## Importing a file with the full names of American states


state_names=np.genfromtxt("state_n1.csv", delimiter=";",
                          dtype=np.str)
state_abb=np.genfromtxt("state_abrivation.csv", delimiter=";",
                          dtype=np.str)

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/2397863344.py:8: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)
C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/2397863344.py:10: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


In [883]:
np.unique(state_names)

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
       'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
       'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype='<U14')

In [884]:
state_abb

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA',
       'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
       'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT',
       'VA', 'WA', 'WV', 'WI', 'WY'], dtype='<U2')

In [885]:
## Constructing a dictionary with keys as the abbrivations of the states and full-names as the values


keys_1=list(state_abb)
values_1= list(state_names)
dict_states= dict(zip(keys_1, values_1))
dict_states

{'AL': 'Alabama',
 'AK': 'Alaska',
 'AZ': 'Arizona',
 'AR': 'Arkansas',
 'CA': 'California',
 'CO': 'Colorado',
 'CT': 'Connecticut',
 'DE': 'Delaware',
 'FL': 'Florida',
 'GA': 'Georgia',
 'HI': 'Hawaii',
 'ID': 'Idaho',
 'IL': 'Illinois',
 'IN': 'Indiana',
 'IA': 'Iowa',
 'KS': 'Kansas',
 'KY': 'Kentucky',
 'LA': 'Louisiana',
 'ME': 'Maine',
 'MD': 'Maryland',
 'MA': 'Massachusetts',
 'MI': 'Michigan',
 'MN': 'Minnesota',
 'MS': 'Mississippi',
 'MO': 'Missouri',
 'MT': 'Montana',
 'NE': 'Nebraska',
 'NV': 'Nevada',
 'NH': 'New Hampshire',
 'NJ': 'New Jersey',
 'NM': 'New Mexico',
 'NY': 'New York',
 'NC': 'North Carolina',
 'ND': 'North Dakota',
 'OH': 'Ohio',
 'OK': 'Oklahoma',
 'OR': 'Oregon',
 'PA': 'Pennsylvania',
 'RI': 'Rhode Island',
 'SC': 'South Carolina',
 'SD': 'South Dakota',
 'TN': 'Tennessee',
 'TX': 'Texas',
 'UT': 'Utah',
 'VT': 'Vermont',
 'VA': 'Virginia',
 'WA': 'Washington',
 'WV': 'West Virginia',
 'WI': 'Wisconsin',
 'WY': 'Wyoming'}

In [886]:
## Replacing with the full state names


for i in keys_1:
    data_string[:,5]= np.where(data_string[:,5]==i,
                               dict_states[i],
                               data_string[:,5])
np.unique(data_string[:,5])

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'DC',
       'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Illinois', 'Indiana', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'red_flag'], dtype='<U69')

In [887]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [888]:
data_string

array([['May', 'OK', '36', '13', 'OK', 'California'],
       ['red_flag', 'OK', '36', '5', 'OK', 'New York'],
       ['Sep', 'OK', '36', '10', 'OK', 'Pennsylvania'],
       ...,
       ['Jun', 'OK', '36', '5', 'OK', 'California'],
       ['Apr', 'OK', '36', '17', 'OK', 'Ohio'],
       ['Dec', 'OK', '36', '4', 'red_flag', 'Illinois']], dtype='<U69')

# Manipulating Numeric Data

In [889]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [890]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [891]:
np.isin(data_numeric, temporary_fill).sum()

8005

## ID

In [892]:
np.isin(data_numeric[:,0], temporary_fill).sum()

0

In [893]:
raw_stats[:,col_numeric]

array([[68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ]])

## Funded Amount

In [894]:
data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [895]:
np.isin(data_numeric[:,2], temporary_fill).sum()

500

In [896]:
## filling the missing values with minimum value of the column using the raw_stats array
## created earlier


data_numeric[:,2] = np.where(data_numeric[:,2]==temporary_fill,
                              raw_stats[0,col_numeric[2]],
                              data_numeric[:,2])
np.isin(data_numeric[:,2], temporary_fill).sum()

0

## Loan amount, Interest rate, Installments and Total payment

In [897]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [898]:
## filling the missing values with mean value of the column using the raw_stats array
## created earlier

for i in [1, 3 ,4, 5]:
    data_numeric[:,i] = np.where(data_numeric[:,i]==temporary_fill,
                                  raw_stats[1, col_numeric[i]],
                                  data_numeric[:,i])

np.isin(data_numeric, temporary_fill).sum()  

0

# Adding Exchange rates

In [899]:
## Importing the file containing the exchange rates between USD and Euros


Eur_usd = np.genfromtxt("EUR-USD.csv", delimiter=",", autostrip=True, skip_header=1, usecols=3)
Eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [900]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [901]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [902]:
## Creating a new array ex_rates containing all the months 


ex_rates= data_string[:,0]
np.unique(ex_rates)

array(['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep',
       'red_flag'], dtype='<U69')

In [903]:
## Constructing a dictionary with months as keys and corresponding exchange rates 
## as values.


k=list(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
v= list(Eur_usd)
dict_ex= dict(zip(k,v))
dict_ex

{'Jan': 1.1287955045700073,
 'Feb': 1.1205360889434814,
 'Mar': 1.0830246210098267,
 'Apr': 1.1114321947097778,
 'May': 1.0960345268249512,
 'Jun': 1.122296690940857,
 'Jul': 1.0939244031906128,
 'Aug': 1.1340054273605347,
 'Sep': 1.1255937814712524,
 'Oct': 1.100897192955017,
 'Nov': 1.0583018064498901,
 'Dec': 1.093398094177246}

In [904]:
## Substituting the corresponding exchange rate values for each month


for i in k:
    ex_rates=np.where(ex_rates==i,
                      dict_ex[i],
                      ex_rates)


## The field where month is not mentioned, we will consider the exchange rate to be 
## the mean of all exchange rates.


ex_rates= np.where(ex_rates=='red_flag',
                   np.mean(Eur_usd),
                   ex_rates)
ex_rates

array(['1.0960345268249512', '1.1056866943836212', '1.1255937814712524', ..., '1.122296690940857',
       '1.1114321947097778', '1.093398094177246'], dtype='<U69')

In [905]:
## Converting the rates into float values


ex_rates=ex_rates.astype(np.float)
ex_rates

C:\Users\Tushar\AppData\Local\Temp/ipykernel_9360/220664133.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ex_rates=ex_rates.astype(np.float)


array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [906]:
ex_rates.shape

(10000,)

In [907]:
ex_rates=np.reshape(ex_rates,(10000,1))

In [908]:
ex_rates.shape

(10000, 1)

In [909]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [910]:
vals_tobe_converted = np.array([1,2,4,5])

In [911]:
## Creating a new array of the values to be converted into Euros


cols_dollars= data_numeric[:, vals_tobe_converted]
cols_dollars

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,   440.92,  2185.64],
       [15273.46, 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [912]:
## Converting USD(US-Dollar) to Euro


cols_dollars=cols_dollars/ex_rates
cols_dollars

array([[31933.3 , 31933.3 ,  1081.04,  8624.69],
       [27132.46, 27132.46,   848.86,  4232.39],
       [13326.3 , 13326.3 ,   439.64,  1750.04],
       ...,
       [ 8910.3 ,  8910.3 ,   392.87,  1947.47],
       [13742.15,  8997.4 ,   318.78,  2878.63],
       [ 9145.8 ,  9145.8 ,   283.49,   276.11]])

In [913]:
## Adding new header for the converted values


header_usd = np.array([col_name + '_USD' for col_name in header_numeric[vals_tobe_converted]])
header_usd

array(['loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'], dtype='<U15')

In [914]:
## Merging the headers of all numeric values


header_numeric= np.concatenate((header_numeric,header_usd))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'loan_amnt_USD',
       'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'], dtype='<U19')

In [915]:
## Combining headers and the data using horizontal stacking of numpy


data_numeric= np.hstack((data_numeric, cols_dollars))
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,      392.87,     1947.47],
       [46154151.  ,    15273.46,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [916]:
## Adding the exchage rate columns to the numeric data


data_numeric=np.hstack((data_numeric,ex_rates))

In [917]:
header_numeric[vals_tobe_converted]= np.array([col_name + '_EUR' for col_name in header_numeric[vals_tobe_converted]])
header_numeric

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'], dtype='<U19')

In [918]:
header_numeric= np.concatenate((header_numeric,np.array(['exch_rate'])))
header_numeric

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD', 'exch_rate'],
      dtype='<U19')

In [919]:
## Rearranging the columns


columns_index_order = [0,1,6,2,7,3,4,8,5,9,10]
header_numeric = header_numeric[columns_index_order]
header_numeric

array(['id', 'loan_amnt_EUR', 'loan_amnt_USD', 'funded_amnt_EUR', 'funded_amnt_USD', 'int_rate',
       'installment_EUR', 'installment_USD', 'total_pymnt_EUR', 'total_pymnt_USD', 'exch_rate'],
      dtype='<U19')

In [920]:
data_numeric = data_numeric[:,columns_index_order]
data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    15273.46,    13742.15, ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [921]:
## Combining the data of both string and numeric columns

loan_data_final= np.hstack((data_numeric, data_string))
loan_data_final

array([['48010226.0', '35000.0', '31933.300588066133', ..., '13', 'OK', 'California'],
       ['57693261.0', '30000.0', '27132.459992858894', ..., '5', 'OK', 'New York'],
       ['59432726.0', '15000.0', '13326.299635729729', ..., '10', 'OK', 'Pennsylvania'],
       ...,
       ['50415990.0', '10000.0', '8910.299817080173', ..., '5', 'OK', 'California'],
       ['46154151.0', '15273.463157894737', '13742.145702269325', ..., '17', 'OK', 'Ohio'],
       ['66055249.0', '10000.0', '9145.799735022167', ..., '4', 'red_flag', 'Illinois']],
      dtype='<U69')

In [922]:
loan_data_final.shape

(10000, 17)

In [923]:
## Combining the headers of both string and numeric data


comp_header= np.concatenate((header_numeric, header_strings))
comp_header

array(['id', 'loan_amnt_EUR', 'loan_amnt_USD', 'funded_amnt_EUR', 'funded_amnt_USD', 'int_rate',
       'installment_EUR', 'installment_USD', 'total_pymnt_EUR', 'total_pymnt_USD', 'exch_rate',
       'issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [924]:
## Merging the complete data 


loan_data_final= np.vstack((comp_header, loan_data_final))
loan_data_final

array([['id', 'loan_amnt_EUR', 'loan_amnt_USD', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['48010226.0', '35000.0', '31933.300588066133', ..., '13', 'OK', 'California'],
       ['57693261.0', '30000.0', '27132.459992858894', ..., '5', 'OK', 'New York'],
       ...,
       ['50415990.0', '10000.0', '8910.299817080173', ..., '5', 'OK', 'California'],
       ['46154151.0', '15273.463157894737', '13742.145702269325', ..., '17', 'OK', 'Ohio'],
       ['66055249.0', '10000.0', '9145.799735022167', ..., '4', 'red_flag', 'Illinois']],
      dtype='<U69')

In [925]:
## Saving as CSV

np.savetxt("loan-data-final-preprocessed.csv", 
           loan_data_final, 
           fmt = '%s',
           delimiter = ',')

In [926]:
## Using pandas to display the complete data in a more orgnised manner


import pandas as pd

# Data before cleaning

In [927]:
before_preprocessing = pd.read_csv("loan-data_13.csv",delimiter=";", delim_whitespace=False)
before_preprocessing.head()

id issue_d  loan_amnt loan_status  funded_amnt        term int_rate  \
0  48010226  May-15    35000.0     Current      35000.0   36 months    13.33   
1  57693261     NaN    30000.0     Current      30000.0   36 months   þëè.89   
2  59432726  Sep-15    15000.0     Current      15000.0   36 months   íîå.53   
3  53222800  Jul-15     9600.0     Current       9600.0   36 months   þëè.89   
4  57803010  Aug-15     8075.0     Current       8075.0   36 months    19.19   

  installment grade sub_grade verification_status  \
0     1184.86     C        C3            Verified   
1      938.57     A        A5     Source Verified   
2      494.86     B        B5            Verified   
3      300.35     A        A5        Not Verified   
4      296.78   NaN        E3     Source Verified   

                                                 url addr_state  total_pymnt  
0  https://www.lendingclub.com/browse/loanDetail....         CA      9452.96  
1  https://www.lendingclub.com/browse/loanDetail....         NY      4679.70  
2  https://www.lendingclub.com/browse/loanDetail....         PA      1969.83  
3  https://www.lendingclub.com/browse/loanDetail....         OH      1793.68  
4  https://www.lendingclub.com/browse/loanDetail....         TX      1178.51

# Data after cleaning

In [928]:
preprocessed_loan= pd.read_csv("loan-data-final-preprocessed.csv")
preprocessed_loan.head()

id  loan_amnt_EUR  loan_amnt_USD  funded_amnt_EUR  funded_amnt_USD  \
0  48010226.0        35000.0   31933.300588          35000.0     31933.300588   
1  57693261.0        30000.0   27132.459993          30000.0     27132.459993   
2  59432726.0        15000.0   13326.299636          15000.0     13326.299636   
3  53222800.0         9600.0    8775.743527           9600.0      8775.743527   
4  57803010.0         8075.0    7120.777207           8075.0      7120.777207   

    int_rate  installment_EUR  installment_USD  total_pymnt_EUR  \
0  13.330000          1184.86      1081.042587          9452.96   
1  16.617295           938.57       848.857099          4679.70   
2  16.617295           494.86       439.643509          1969.83   
3  16.617295           300.35       274.561934          1793.68   
4  19.190000           296.78       261.709506          1178.51   

   total_pymnt_USD  exch_rate issue_date loan_status  term sub_grade  \
0      8624.691804   1.096035        May          OK    36        13   
1      4232.392434   1.105687   red_flag          OK    36         5   
2      1750.036321   1.125594        Sep          OK    36        10   
3      1639.674547   1.093924        Jul          OK    36         5   
4      1039.245467   1.134005        Aug          OK    36        23   

  verification_status    addr_state  
0                  OK    California  
1                  OK      New York  
2                  OK  Pennsylvania  
3            red_flag          Ohio  
4                  OK         Texas